fixtures:
  repositories:
    stdlib:  https://github.com/puppetlabs/puppetlabs-stdlib.git
    powershell:  https://github.com/joshcooper/puppetlabs-powershell.git
    win_facts:  https://github.com/liamjbennett/puppet-win_facts.git
